### ISSUE TITLE
Cannot install napari organoid counter as a plugin

### ISSUE THREAD

**Issue by ozcelikelif** [HelmholtzAI-Consultants-Munich/napari-organoid-counter#1]
Hi, after opening napari as a python package in my terminal I have tried to install organoid counter as can be seen from the picture. After I press install, it never finishes and renews the page. I have downloaded aicsimageio too. Its not showing up in my plugins section. 

<img width="1159" alt="Screen Shot 2022-07-21 at 11 19 49 AM" src="https://user-images.githubusercontent.com/72396952/180251083-cb69c45e-2dbe-4a9d-80a1-1f29646a3b49.png">

Thanks a lot,

**Comment by christinab12** [comment]
Hi @elifozcelik I just see you closed this issue, did you figure this out?
