### ISSUE TITLE
Docs: Explanation of Window sizes and downsampling

### ISSUE THREAD

**Issue by Theresa-S** [HelmholtzAI-Consultants-Munich/napari-organoid-counter#10]
What effect do both parameters have on the detection results?
In my specific case: if I want to detect smaller organoids, how do I best tune the parameters?

**Comment by christinab12** [comment]
Hi @Theresa-S,

I have added an explanation in point 5: https://github.com/HelmholtzAI-Consultants-Munich/napari-organoid-counter/blob/christinab12-fixes-from-user-testing/.napari/DESCRIPTION.md#quickstart

Do you think it is this clear now?

**Comment by christinab12** [comment]
closing this for now, as it is covered by extra documentation and info window on hover in #17
