### ISSUE TITLE
bunch of UX issues / lack of user feedback / freezes / documentation

### ISSUE THREAD

**Issue by neuronflow** [HelmholtzAI-Consultants-Munich/napari-organoid-counter#11]
as discussed:

```
I try to open a terminal and type napari…I press enter it is processing for ~30s now
[5:57](https://comp-health.slack.com/archives/D04UK3JRVMG/p1683043032435819)
now I see a loading window, oh there is an icon
[6:00](https://comp-health.slack.com/archives/D04UK3JRVMG/p1683043209844529)
I drag and drop the file to load the image..on the top I press on plugin -> orga counter…it opens a window I press a run button and the window freezes and becomes unresponsive in the terminal I see it is downloading something :slightly_smiling_face:
[6:03](https://comp-health.slack.com/archives/D04UK3JRVMG/p1683043383102359)
now I see this
```

![image](https://user-images.githubusercontent.com/7048826/235961990-3fed98c2-5e05-4498-9752-27ecb271a95c.png)
```
I now set downsampling to 0 and pressed the run button again, app becomes unresponsive and I see a wheel of fortune
[6:09](https://comp-health.slack.com/archives/D04UK3JRVMG/p1683043750965129)
it is responsive again…a more graceful user feedback, for instance a progress bar would be nice
[6:09](https://comp-health.slack.com/archives/D04UK3JRVMG/p1683043769490399)
I just noticed there is a preprocessing button, maybe I should have pressed this before
[6:09](https://comp-health.slack.com/archives/D04UK3JRVMG/p1683043790163159)
I have no idea what are meaningful values for downsampling (consider adding small help boxes) displaying overlays
[6:10](https://comp-health.slack.com/archives/D04UK3JRVMG/p1683043830299679)
after save I have a drop down menu with only 1 option
[6:10](https://comp-health.slack.com/archives/D04UK3JRVMG/p1683043855601629)
when selecting the cpt file I notice the software has invaded my disk and downloaded files to my computer
[6:13](https://comp-health.slack.com/archives/D04UK3JRVMG/p1683044029395319)
I drag and drop two more files and I dare to run the model again…
[6:14](https://comp-health.slack.com/archives/D04UK3JRVMG/p1683044044609269)
ah it created labels for only 1..is there a way to run batch inference?
```

![image](https://user-images.githubusercontent.com/7048826/235962165-4e384bfe-4f4e-4de2-8fa7-9fb0298a9677.png)
```
this list should be sorted / grouped to show pairs that belong together
```

**Comment by christinab12** [comment]
Summarising suggested changes here:
* Have some indication that sw is busy after clicking run button: a more graceful user feedback, for instance a progress bar would be nice (window freezes and becomes unresponsive, in the terminal I see it is downloading something)
* I have no idea what are meaningful values for downsampling (consider adding small help boxes) displaying overlays
* the layer list should be sorted / grouped to show pairs that belong together
* after save I have a drop down menu with only 1 option
* when selecting the cpt file I notice the software has invaded my disk and downloaded files to my computer
* is there a way to run for multiple input images simultaneously?

**Comment by christinab12** [comment]
Addressing each of the suggested changes above:
* Have some indication that sw is busy after clicking run button -> created #12 
* Consider adding small help boxes -> created #13 
* the layer list should be sorted / grouped to show pairs that belong together -> created #15 
* after save I have a drop down menu with only 1 option -> close: there are as many options as label layers
* is there a way to run for multiple input images simultaneously? -> no, no plans to do this for now
* when selecting the cpt file I notice the software has invaded my disk and downloaded files to my computer -> true, not sure what to do about that, as good to keep model weights locally so you don't have to download again when re-using software. @neuronflow ideas here?

**Comment by christinab12** [comment]
closing this issue now as the points have either been addressed in separate issues or will not be addressed
