### ISSUE TITLE
Organoid counter not working

### ISSUE THREAD

**Issue by ozcelikelif** [HelmholtzAI-Consultants-Munich/napari-organoid-counter#2]
Hi I have been getting the following error: **ValueError: `block_size` must be a scalar or have the same length as `image.shape`**
every-time I try to use the run organoid counter button. Do you know how can I solve it? Thanks.

**Comment by christinab12** [comment]
Hi @elifozcelik, have you changed the downsampling value to a non-integer number? Where are you running this?

**Comment by christinab12** [comment]
I just encountered the same issue. The problem for me was that the input image had more than two dimensions (current version only accepts grayscale image with heights, width dims). I will add a new version allowing for more dims and small changes soon.
