### ISSUE TITLE
Update to use qtpy imports

### ISSUE THREAD

**Issue by goanpeca** [HelmholtzAI-Consultants-Munich/napari-organoid-counter#23]
Hello team!

The plugin documentation for napari has a set of best practices for developers, which includes a clause recommending not to depend directly on PyQt5 or PySide2 to allow end-users to choose their bindings freely. [More details here](https://napari.org/stable/plugins/best_practices.html#don-t-include-pyside2-or-pyqt5-in-your-plugin-s-dependencies).

The files using `PyQt5` instead of `qtpy` are listed here -> https://github.com/HelmholtzAI-Consultants-Munich/napari-organoid-counter/blob/224eff90e17cc5a62353e04f179cfe2d39969b4e/napari_organoid_counter/_widget.py#L9

Also I suggest you do not use the `*` import. That is generally not recommended

Some options might include changing this code 

```python
from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import *
```

To 

1. 
```python
from qtpy.QtCore import Qt
from qtpy.QtWidgets import QWidget   # and explicitely list everything that is needed
```

Or to

2. 
```python
from qtpy import QtCore
from qtpy import QtWidgets

# And then use it like

class OrganoidCounterWidget(QtWidgets.QWidget):
```

I favor option 1 as it is more explicit in what needs to be imported for a given module.

Is there a reason you need PyQt5 explicitly? Could these imports be updated to use `qtpy` for the next release?

If you have questions, or need some help, let me know :) 

Thanks! 🚀

**Comment by christinab12** [comment]
Thanks so much for your tips @goanpeca! #25 includes these changes, I will push a new version now :)
