### ISSUE TITLE
Update dependencies?

### ISSUE THREAD

**Issue by goanpeca** [HelmholtzAI-Consultants-Munich/napari-organoid-counter#24]
Hi team, while working on https://github.com/conda-forge/napari-organoid-counter-feedstock/pull/1

We noticed that there is this requirement `zenodo_get==1.3.4`, but I have not find anywhere in the source code where it is used. Is this needed?

Also if it is indeed needed, is there a reason for the exact pin? could this be relaxed to either `<=` or `>=`

Cheers 🚀 !

**Comment by christinab12** [comment]
Thanks @goanpeca, you are right, this was left over from a previous version. I have removed now in #25
