### ISSUE TITLE
Information on output

### ISSUE THREAD

**Issue by Theresa-S** [HelmholtzAI-Consultants-Munich/napari-organoid-counter#4]
Hey @christinab12 ,

I'm currently testing the tool and was wondering:
- How is the area of the organoid calculated? Do you take the length/ width of the bounding box for the elipse area?
- Is there a way to assign the organoid ID to the organoids in the original image? I would like to check if outliers make sense or not.

Best,
Theresa

PS: the link to the older version is unfortunately broken :-/

**Comment by christinab12** [comment]
Hi @Theresa-S ,

Thanks for your interest. Here a reply to your questions:

* Yes we take the height and width of the bounding boxes to calculate the area of the organoid and approximate that to an ellipse.
* Yes sorry about that, this repo has been changed to private, so I will have to change here. Are you interested in seeing the code of the older version or do you need more background info?
* "Is there a way to assign the organoid ID to the organoids in the original image? I would like to check if outliers make sense or not" Do you mean that you would like the OrganoidID you get in the features.csv file to be visible also on the image so you can match the organoids in the image to the diameters?

Best,
Christina

**Comment by Theresa-S** [comment]
Hey Christina,

thank you for your fast answers!
I don't need to see the old code, just some background information so that I understand what the code is doing and what the output actually means.

Yes, you're correct, I would like to match the organoids in the image to the measurements in the csv. 

Do you have experience with other organoid lines? Mine are from colon, and while I found the parameter combination to get the best possible result in Napare, I'm not 100% happy with the output. Do you have any recommendations for preprocessing? Or image acquisition for that matter (even though there I'm somewhat restricted)? So far, the only step is calculating an extended depth of field over a z-stack of 5 slices (at 200 µm distance).

Did you try follow-up over time?

Best,
Theresa

**Comment by christinab12** [comment]
Hi Theresa,

In the seconds paragraph of the "Quickstart" section [here](https://www.napari-hub.org/plugins/napari-organoid-counter) you can read what the outputs of the tool are.

I don't have much information on the background of the data I'm afraid. Here's what I can tell you:
* Our users are working with lung organoids
* They also apply the extended depth of focus algorithm as a preprocessing step
* They are using a 5x objective and have two types of organoids

To make any suggestions to you (if I were to have any), it would be easier to first see an example of your images.

Our collaborators who are currently using the tool, also need to make corrections on the output around 30-40% of the time. For the them, however, this is still a gain, as before they were counting all organoids manually, and the big benefit is that they now get the size output now for downstream analysis. I'm afraid I do not know if this is being used for follow-ups over time.

The most interesting news for you perhaps is that we are currently working on improving this too (it now uses standard image processing techniques like edge detection and thresholding in the back-end). We are developing a deep learning solution which will hopefully be ready for release by early spring. In this new version of the tool we can also integrate matching the organoID with the organoids in the image.

Hope this was helpful.

Best,
Christina

**Comment by christinab12** [comment]
One more point I just thought of, for now you could match the organoid ID in the csv file (which gives you the diameters), with the locations of the boxes from the json file (the ids are the same).

**Comment by Theresa-S** [comment]
Thank you for your replies! 
Since I have an existing organoid segmentation pipeline I will wait for the new and improved version :-)
Feel free to contact me if you need an alpha tester.

Best,
Theresa
