### ISSUE TITLE
Strange thickness of the bounding boxes

### ISSUE THREAD

**Issue by Theresa-S** [HelmholtzAI-Consultants-Munich/napari-organoid-counter#5]
Is there a way to change the border thickness of the bounding boxes? Or at least standardize them all to the same size?
![image](https://user-images.githubusercontent.com/61883896/207882881-3afc5716-06c4-4d04-88b0-a41a3934909c.png)

**Comment by christinab12** [comment]
Hi @Theresa-S,

We have noticed this occurs when you play around with the downsampling parameter and detect organoids at different downsampling values. Was this the case? In any case it should be fixed, I will try and work on this next week!

Best,
Christina

**Comment by Theresa-S** [comment]
Exactly what happened! Thanks for the clarification.

**Comment by christinab12** [comment]
Hi @Theresa-S,

I have just pushed a new version in which this problem above should be solved. There are also quite a few changes, you can check these out [here](https://github.com/HelmholtzAI-Consultants-Munich/napari-organoid-counter/blob/main/.napari/DESCRIPTION.md#whats-new-in-v2). I would be more than happy if you were to test the new version and let me know if you have any feedback!  I'll close this issue now, but feel free to open a new one if there is anything in the new version which isn't working for you. 

Thanks,
Christina
