### ISSUE TITLE
Manual entering of parameters

### ISSUE THREAD

**Issue by Theresa-S** [HelmholtzAI-Consultants-Munich/napari-organoid-counter#8]
While I really like the sliders, I find it tricky to accurately choose specific values in the parameter box - maybe a question of taste, but I would prefer to enter values (as in the input configurations box) or have both options.

**Comment by christinab12** [comment]
Addressed in https://github.com/HelmholtzAI-Consultants-Munich/napari-organoid-counter/commit/041ef830ec75c857016bf79d36da8bb6a44312b1

Will be added to next release
